# Traefik demo for docker-compose
#
# Launch with :
#   docker-compose up
#
# Traefik Dashboard is avaibale at :
#   http://localhost:8080
#
#
# Services will be accessible at :
#
#   - whoami1 => curl -H host:whoami1.traefik
#   - whoami2 => curl -H host:whoami2.traefik

version: '3'

services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
     - "80:80"
     - "8080:8080"
    volumes: 
     - /var/run/docker.sock:/var/run/docker.sock
    command: traefik --docker  --docker.domain=traefik --docker.watch --web --logLevel=DEBUG
    networks:
      - traefik-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  whoami1:
    image: emilevauge/whoami
    networks:
      - traefik-net
    labels:
      - "traefik.frontend.rule=Host:whoami1.traefik"
      # - "traefik.frontend.rule=Host:whoami.traefik; PathPrefixStrip: /whoami1"

  whoami2:
    image: emilevauge/whoami
    networks:
      - traefik-net
    labels:
      - "traefik.frontend.rule=Host:whoami2.traefik"
      # - "traefik.frontend.rule=Host:whoami.traefik; PathPrefixStrip: /whoami2"

networks:
  traefik-net:
    driver: overlay
