# https://github.com/SvenDowideit/docs-automation/blob/master/jenkins/setup-docker-and-start-jenkins.sh - configure
# socat TCP-LISTEN:2376,range=0.0.0.0/0,reuseaddr,fork UNIX:/var/run/docker.sock
version: '3'

services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
     - "80:80"
     - "8080:8080"
    volumes: 
     - /var/run/docker.sock:/var/run/docker.sock
    command: traefik --docker --docker.swarmmode --docker.domain=traefik --docker.watch --web --logLevel=DEBUG
    networks:
      - traefik-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  whoami1:
    image: emilevauge/whoami
    networks:
      - traefik-net
    labels:
      - "traefik.frontend.rule=Host:whoami1.traefik"

  whoami2:
    image: emilevauge/whoami
    networks:
      - traefik-net
    labels:
      - "traefik.frontend.rule=Host:whoami2.traefik"

networks:
  traefik-net:
    driver: overlay
