
version: '3'

services:
  traefik:
    image: traefik
    ports:
     - "80:80"
     - "8080:8080"
    volumes: 
     - /var/run/docker.sock:/var/run/docker.sock
    command: traefik --docker --docker.swarmmode --docker.domain=traefik --docker.watch --web --logLevel=DEBUG
    networks:
      - traefik-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-net
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.docker.network=pic_traefik-net"
        - "traefik.frontend.rule=Host:jenkins.traefik"
        - "traefik.frontend.passHostHeader=true"
      placement:
        constraints:
          - node.role == manager

  nexus:
    image: sonatype/nexus3
    volumes:
      - nexus-data:/nexus-data
    networks:
      - traefik-net
    # environment:
    #   - NEXUS_CONTEXT="nexus"
    deploy:
      labels:
        - "traefik.port=8081"
        - "traefik.docker.network=pic_traefik-net"
        - "traefik.frontend.rule=PathStrip: /nexus"
        - "traefik.frontend.passHostHeader=true"
      placement:
        constraints:
          - node.role == manager

  # sonar:
  #   image: sonarqube:alpine
  #   container_name: sonar
  #   labels:
  #     - "traefik.enable=false"
  #   networks:
  #     - traefik-net

volumes:
  jenkins-data:
  nexus-data:

networks:
  traefik-net:
    # external: true
    driver: overlay
